<a href="https://colab.research.google.com/github/tripti-bhardwaj/Deep_Learning_Lab/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Fundamentals of Tensor Operations using PyTorch and NumPy
Create 1D, 2D, and 3D tensors using PyTorch and NumPy. Show Basic Operations: Element-wise addition, subtraction, multiplication, and division. Dot product and matrix multiplication. Indexing and Slicing examples (Boolean masking, extracting subtensors) Use .view(), .reshape(), .unsqueeze(), and .squeeze() in PyTorch. Compare with .reshape in Numpy Broadcasting- Perform operations with tensors of different shapes. In-place vs Out-of-place operations


## Create Tensors

In [ ]:
import numpy as np
import torch

# 1. Create 1D PyTorch tensor and NumPy array
pt_tensor_1d = torch.tensor([1, 2, 3])
np_array_1d = np.array([4, 5, 6])
print('1D PyTorch Tensor:\n', pt_tensor_1d)
print('1D NumPy Array:\n', np_array_1d)

# 2. Create 2D PyTorch tensor and NumPy array
pt_tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
np_array_2d = np.array([[7, 8, 9], [10, 11, 12]])
print('\n2D PyTorch Tensor:\n', pt_tensor_2d)
print('2D NumPy Array:\n', np_array_2d)

# 3. Create 3D PyTorch tensor and NumPy array
pt_tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
np_array_3d = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
print('\n3D PyTorch Tensor:\n', pt_tensor_3d)
print('3D NumPy Array:\n', np_array_3d)

1D PyTorch Tensor:
 tensor([1, 2, 3])
1D NumPy Array:
 [4 5 6]

2D PyTorch Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
2D NumPy Array:
 [[ 7  8  9]
 [10 11 12]]

3D PyTorch Tensor:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
3D NumPy Array:
 [[[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


## Basic Arithmetic Operations


In [ ]:
pt_tensor_1d_b = torch.tensor([5, 6, 7])
print('1D PyTorch Tensor b:\n', pt_tensor_1d_b)

print('\nPyTorch Element-wise Addition:', pt_tensor_1d + pt_tensor_1d_b)
print('PyTorch Element-wise Subtraction:', pt_tensor_1d - pt_tensor_1d_b)
print('PyTorch Element-wise Multiplication:', pt_tensor_1d * pt_tensor_1d_b)
print('PyTorch Element-wise Division:', pt_tensor_1d / pt_tensor_1d_b)

np_array_1d_b = np.array([8, 9, 10])
print('\n1D NumPy Array b:\n', np_array_1d_b)

print('\nNumPy Element-wise Addition:', np_array_1d + np_array_1d_b)
print('NumPy Element-wise Subtraction:', np_array_1d - np_array_1d_b)
print('NumPy Element-wise Multiplication:', np_array_1d * np_array_1d_b)
print('NumPy Element-wise Division:', np_array_1d / np_array_1d_b)

1D PyTorch Tensor b:
 tensor([5, 6, 7])

PyTorch Element-wise Addition: tensor([ 6,  8, 10])
PyTorch Element-wise Subtraction: tensor([-4, -4, -4])
PyTorch Element-wise Multiplication: tensor([ 5, 12, 21])
PyTorch Element-wise Division: tensor([0.2000, 0.3333, 0.4286])

1D NumPy Array b:
 [ 8  9 10]

NumPy Element-wise Addition: [12 14 16]
NumPy Element-wise Subtraction: [-4 -4 -4]
NumPy Element-wise Multiplication: [32 45 60]
NumPy Element-wise Division: [0.5        0.55555556 0.6       ]


## Dot Product and Matrix Multiplication

In [ ]:
print('PyTorch Dot Product:')
pt_tensor_1d_c = torch.tensor([1, 2, 3])
pt_tensor_1d_d = torch.tensor([4, 5, 6])
print('1D PyTorch Tensor c:', pt_tensor_1d_c)
print('1D PyTorch Tensor d:', pt_tensor_1d_d)
print('PyTorch Dot Product (torch.dot):', torch.dot(pt_tensor_1d_c, pt_tensor_1d_d))

print('\nPyTorch Matrix Multiplication:')
pt_matrix_a = torch.tensor([[1, 2], [3, 4]])
pt_matrix_b = torch.tensor([[5, 6], [7, 8]])
print('2D PyTorch Matrix a:\n', pt_matrix_a)
print('2D PyTorch Matrix b:\n', pt_matrix_b)
print('PyTorch Matrix Multiplication (torch.matmul):\n', torch.matmul(pt_matrix_a, pt_matrix_b))
print('PyTorch Matrix Multiplication (@ operator):\n', pt_matrix_a @ pt_matrix_b)

print('\nNumPy Dot Product:')
np_array_1d_c = np.array([1, 2, 3])
np_array_1d_d = np.array([4, 5, 6])
print('1D NumPy Array c:', np_array_1d_c)
print('1D NumPy Array d:', np_array_1d_d)
print('NumPy Dot Product (np.dot):', np.dot(np_array_1d_c, np_array_1d_d))

print('\nNumPy Matrix Multiplication: ')
np_matrix_a = np.array([[1, 2], [3, 4]])
np_matrix_b = np.array([[5, 6], [7, 8]])
print('2D NumPy Array a:\n', np_matrix_a)
print('2D NumPy Array b:\n', np_matrix_b)
print('NumPy Matrix Multiplication (np.matmul):\n', np.matmul(np_matrix_a, np_matrix_b))
print('NumPy Matrix Multiplication (@ operator):\n', np_matrix_a @ np_matrix_b)

PyTorch Dot Product:
1D PyTorch Tensor c: tensor([1, 2, 3])
1D PyTorch Tensor d: tensor([4, 5, 6])
PyTorch Dot Product (torch.dot): tensor(32)

PyTorch Matrix Multiplication:
2D PyTorch Matrix a:
 tensor([[1, 2],
        [3, 4]])
2D PyTorch Matrix b:
 tensor([[5, 6],
        [7, 8]])
PyTorch Matrix Multiplication (torch.matmul):
 tensor([[19, 22],
        [43, 50]])
PyTorch Matrix Multiplication (@ operator):
 tensor([[19, 22],
        [43, 50]])

NumPy Dot Product:
1D NumPy Array c: [1 2 3]
1D NumPy Array d: [4 5 6]
NumPy Dot Product (np.dot): 32

NumPy Matrix Multiplication: 
2D NumPy Array a:
 [[1 2]
 [3 4]]
2D NumPy Array b:
 [[5 6]
 [7 8]]
NumPy Matrix Multiplication (np.matmul):
 [[19 22]
 [43 50]]
NumPy Matrix Multiplication (@ operator):
 [[19 22]
 [43 50]]


## Indexing and Slicing

In [ ]:
print('PyTorch Indexing and Slicing: ')
pt_data = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print('Original PyTorch Tensor:\n', pt_data)

print('\nAccessing single element pt_data[0, 1]:', pt_data[0, 1])
print('Accessing full row pt_data[1, :]:', pt_data[1, :])
print('Accessing full column pt_data[:, 2]:', pt_data[:, 2])
print('Extracting sub-tensor pt_data[0:2, 0:2]:\n', pt_data[0:2, 0:2])
print('Boolean masking (elements > 50):', pt_data[pt_data > 50])

print('\nNumPy Indexing and Slicing:')
np_data = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print('Original NumPy Array:\n', np_data)

print('\nAccessing single element np_data[0, 1]:', np_data[0, 1])
print('Accessing full row np_data[1, :]:', np_data[1, :])
print('Accessing full column np_data[:, 2]:', np_data[:, 2])
print('Extracting sub-array np_data[0:2, 0:2]:\n', np_data[0:2, 0:2])
print('Boolean masking (elements > 50):', np_data[np_data > 50])

PyTorch Indexing and Slicing: 
Original PyTorch Tensor:
 tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

Accessing single element pt_data[0, 1]: tensor(20)
Accessing full row pt_data[1, :]: tensor([40, 50, 60])
Accessing full column pt_data[:, 2]: tensor([30, 60, 90])
Extracting sub-tensor pt_data[0:2, 0:2]:
 tensor([[10, 20],
        [40, 50]])
Boolean masking (elements > 50): tensor([60, 70, 80, 90])

NumPy Indexing and Slicing:
Original NumPy Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Accessing single element np_data[0, 1]: 20
Accessing full row np_data[1, :]: [40 50 60]
Accessing full column np_data[:, 2]: [30 60 90]
Extracting sub-array np_data[0:2, 0:2]:
 [[10 20]
 [40 50]]
Boolean masking (elements > 50): [60 70 80 90]


## Shape Manipulation

In [ ]:
# 1. Create a 2D PyTorch tensor and a 2D NumPy array
pt_original_tensor = torch.arange(1, 10).reshape(3, 3)
np_original_array = np.arange(1, 10).reshape(3, 3)

print('PyTorch Shape Manipulation: \n')
print('Original PyTorch Tensor:\n', pt_original_tensor)
print('Original PyTorch Tensor Shape:', pt_original_tensor.shape)

# 2. PyTorch: .view() and .reshape()
# .view() requires the tensor to be contiguous. If not, .contiguous() should be called first.
# .reshape() can handle non-contiguous tensors by creating a copy if necessary.

# Using .view()
pt_viewed_tensor = pt_original_tensor.view(1, 9)
print('\nPyTorch Tensor after .view(1, 9):\n', pt_viewed_tensor)
print('Shape after .view(1, 9):', pt_viewed_tensor.shape)

# Using .reshape()
pt_reshaped_tensor = pt_original_tensor.reshape(9, 1)
print('\nPyTorch Tensor after .reshape(9, 1):\n', pt_reshaped_tensor)
print('Shape after .reshape(9, 1):', pt_reshaped_tensor.shape)

# 3. PyTorch: .unsqueeze() and .squeeze()
# .unsqueeze()
pt_unsqueezed_tensor = pt_original_tensor.unsqueeze(0) # Add a dimension at axis 0
print('\nPyTorch Tensor after .unsqueeze(0):\n', pt_unsqueezed_tensor)
print('Shape after .unsqueeze(0):', pt_unsqueezed_tensor.shape)

pt_unsqueezed_tensor_2 = pt_original_tensor.unsqueeze(2) # Add a dimension at axis 2
print('\nPyTorch Tensor after .unsqueeze(2):\n', pt_unsqueezed_tensor_2)
print('Shape after .unsqueeze(2):', pt_unsqueezed_tensor_2.shape)

# .squeeze()
# Create a tensor with a singleton dimension to demonstrate .squeeze()
pt_with_singleton = torch.tensor([[[1, 2, 3]]])
print('\nPyTorch Tensor with singleton dimension:\n', pt_with_singleton)
print('Shape of tensor with singleton dimension:', pt_with_singleton.shape)

pt_squeezed_tensor = pt_with_singleton.squeeze()
print('\nPyTorch Tensor after .squeeze():\n', pt_squeezed_tensor)
print('Shape after .squeeze():', pt_squeezed_tensor.shape)

pt_squeezed_tensor_dim0 = pt_with_singleton.squeeze(0)
print('\nPyTorch Tensor after .squeeze(0):\n', pt_squeezed_tensor_dim0)
print('Shape after .squeeze(0):', pt_squeezed_tensor_dim0.shape)

print('\nNumPy Shape Manipulation: \n')
print('Original NumPy Array:\n', np_original_array)
print('Original NumPy Array Shape:', np_original_array.shape)

# 4. NumPy: .reshape()
np_reshaped_array = np_original_array.reshape(1, 9)
print('\nNumPy Array after .reshape(1, 9):\n', np_reshaped_array)
print('Shape after .reshape(1, 9):', np_reshaped_array.shape)

np_reshaped_array_2 = np_original_array.reshape(9)
print('\nNumPy Array after .reshape(9):\n', np_reshaped_array_2)
print('Shape after .reshape(9):', np_reshaped_array_2.shape)


PyTorch Shape Manipulation: 

Original PyTorch Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Original PyTorch Tensor Shape: torch.Size([3, 3])

PyTorch Tensor after .view(1, 9):
 tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
Shape after .view(1, 9): torch.Size([1, 9])

PyTorch Tensor after .reshape(9, 1):
 tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
Shape after .reshape(9, 1): torch.Size([9, 1])

PyTorch Tensor after .unsqueeze(0):
 tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Shape after .unsqueeze(0): torch.Size([1, 3, 3])

PyTorch Tensor after .unsqueeze(2):
 tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])
Shape after .unsqueeze(2): torch.Size([3, 3, 1])

PyTorch Tensor with singleton dimension:
 tensor([[[1, 2, 3]]])
Shape of tensor with singleton dimension: torch.Size([1, 1, 3])

PyTorch Tensor a

## Broadcasting

In [ ]:
print('PyTorch Broadcasting:')
pt_tensor_2d_broad = torch.tensor([[1, 2, 3], [4, 5, 6]])
pt_tensor_1d_broad = torch.tensor([10, 20, 30])

print('Original 2D PyTorch Tensor:\n', pt_tensor_2d_broad)
print('Shape of 2D PyTorch Tensor:', pt_tensor_2d_broad.shape)
print('Original 1D PyTorch Tensor:\n', pt_tensor_1d_broad)
print('Shape of 1D PyTorch Tensor:', pt_tensor_1d_broad.shape)

pt_broadcast_result = pt_tensor_2d_broad + pt_tensor_1d_broad
print('\nResult of PyTorch Broadcasting (2D + 1D):\n', pt_broadcast_result)
print('Shape of Broadcasted PyTorch Result:', pt_broadcast_result.shape)

print('\nNumPy Broadcasting: ')
np_array_2d_broad = np.array([[1, 2, 3], [4, 5, 6]])
np_array_1d_broad = np.array([10, 20, 30])

print('Original 2D NumPy Array:\n', np_array_2d_broad)
print('Shape of 2D NumPy Array:', np_array_2d_broad.shape)
print('Original 1D NumPy Array:\n', np_array_1d_broad)
print('Shape of 1D NumPy Array:', np_array_1d_broad.shape)

np_broadcast_result = np_array_2d_broad + np_array_1d_broad
print('\nResult of NumPy Broadcasting (2D + 1D):\n', np_broadcast_result)
print('Shape of Broadcasted NumPy Result:', np_broadcast_result.shape)

PyTorch Broadcasting:
Original 2D PyTorch Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Shape of 2D PyTorch Tensor: torch.Size([2, 3])
Original 1D PyTorch Tensor:
 tensor([10, 20, 30])
Shape of 1D PyTorch Tensor: torch.Size([3])

Result of PyTorch Broadcasting (2D + 1D):
 tensor([[11, 22, 33],
        [14, 25, 36]])
Shape of Broadcasted PyTorch Result: torch.Size([2, 3])

NumPy Broadcasting: 
Original 2D NumPy Array:
 [[1 2 3]
 [4 5 6]]
Shape of 2D NumPy Array: (2, 3)
Original 1D NumPy Array:
 [10 20 30]
Shape of 1D NumPy Array: (3,)

Result of NumPy Broadcasting (2D + 1D):
 [[11 22 33]
 [14 25 36]]
Shape of Broadcasted NumPy Result: (2, 3)


## In-place vs Out-of-place Operations

In [ ]:

print('PyTorch In-place vs Out-of-place: \n')

# 1. PyTorch In-place Operation
pt_in_place = torch.tensor([1, 2, 3])
scalar_pt = 5
print('Original PyTorch Tensor (in-place):', pt_in_place)
pt_in_place.add_(scalar_pt) # In-place addition
print('PyTorch Tensor after in-place add_:', pt_in_place)

pt_in_place_alt = torch.tensor([10, 20, 30])
print('Original PyTorch Tensor (in-place with +=):', pt_in_place_alt)
pt_in_place_alt += scalar_pt # In-place addition using +=
print('PyTorch Tensor after in-place +=:', pt_in_place_alt)

# 2. PyTorch Out-of-place Operation
pt_out_of_place = torch.tensor([4, 5, 6])
print('\nOriginal PyTorch Tensor (out-of-place):', pt_out_of_place)
pt_result = pt_out_of_place + scalar_pt # Out-of-place addition
print('PyTorch Tensor (original, after out-of-place):', pt_out_of_place) # Original remains unchanged
print('PyTorch Result Tensor (out-of-place):', pt_result) # New tensor created

print('\nNumPy In-place vs Out-of-place: \n')

# 3. NumPy In-place Operation
np_in_place = np.array([1, 2, 3])
scalar_np = 5
print('Original NumPy Array (in-place):', np_in_place)
np_in_place += scalar_np # In-place addition
print('NumPy Array after in-place +=:', np_in_place)

# 4. NumPy Out-of-place Operation
np_out_of_place = np.array([4, 5, 6])
print('\nOriginal NumPy Array (out-of-place):', np_out_of_place)
np_result = np_out_of_place + scalar_np # Out-of-place addition
print('NumPy Array (original, after out-of-place):', np_out_of_place) # Original remains unchanged
print('NumPy Result Array (out-of-place):', np_result) # New array created


PyTorch In-place vs Out-of-place: 

Original PyTorch Tensor (in-place): tensor([1, 2, 3])
PyTorch Tensor after in-place add_: tensor([6, 7, 8])
Original PyTorch Tensor (in-place with +=): tensor([10, 20, 30])
PyTorch Tensor after in-place +=: tensor([15, 25, 35])

Original PyTorch Tensor (out-of-place): tensor([4, 5, 6])
PyTorch Tensor (original, after out-of-place): tensor([4, 5, 6])
PyTorch Result Tensor (out-of-place): tensor([ 9, 10, 11])

NumPy In-place vs Out-of-place: 

Original NumPy Array (in-place): [1 2 3]
NumPy Array after in-place +=: [6 7 8]

Original NumPy Array (out-of-place): [4 5 6]
NumPy Array (original, after out-of-place): [4 5 6]
NumPy Result Array (out-of-place): [ 9 10 11]
